# Only the public devkitPro/newlib/libnx ABI is used. There is no Linux sysroot.
my %targets = (
    "libnx-aarch64" => {
        inherit_from => [ "gcc" ],
        bn_ops => "SIXTY_FOUR_BIT_LONG",
        thread_scheme => "pthreads",
        defines => add("NO_SYSLOG"),
    },
);
